Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)


Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

soln:

there is a difference in the data type of variables list_ and array_list. list_ is a Python list, while array_list is a NumPy array.

To print the data types of both variables, you can use the type() function:

In [1]:


import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print(type(list_))       # <class 'list'>
print(type(array_list))  # <class 'numpy.ndarray'>


<class 'list'>
<class 'numpy.ndarray'>


The type() function returns the data type of the argument passed to it. In this case, the first print() statement shows that the data type of list_ is list, while the second print() statement shows that the data type of array_list is numpy.ndarray.

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

soln:

In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# print data type of each element in list_
for element in list_:
    print(type(element))

# print data type of each element in array_list
for element in array_list:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


the first loop iterates through each element of list_ and prints the data type of each element using the type() function. The second loop iterates through each element of array_list and also prints the data type of each element using the type() function.

Note that since all the elements in both list_ and array_list are strings, the data type of each element will be str.

Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

soln:

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# print data type of each element in list_
for element in list_:
    print(type(element))

# print data type of each element in array_list
for element in array_list:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Yes, there will be a difference in the data type of the elements present in list_ and array_list after applying the dtype=int argument. When dtype is set to int, array_list will be an array of integers instead of an array of strings.

To print the data types of each and every element present in both list_ and array_list, you can use a loop to iterate through each element and apply the type() function to it. 

the first loop iterates through each element of list_ and prints the data type of each element using the type() function. The second loop iterates through each element of array_list and also prints the data type of each element using the type() function.

As for the second part of the question, the variable num_array will be a 2-dimensional NumPy array of integers. The elements in num_list are already integers, so there is no need to specify dtype=int. To print the data types of each element in num_array, you can use a nested loop to iterate through each row and each column of the array, like this:

In [4]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# print data type of each element in num_array
for row in num_array:
    for element in row:
        print(type(element))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

soln:

In [5]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(num_list)

# find the shape of num_array
print("Shape of num_array:", num_array.shape)

# find the size of num_array
print("Size of num_array:", num_array.size)

Shape of num_array: (2, 3)
Size of num_array: 6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

soln:

In [6]:
import numpy as np

# create a 3x3 matrix containing only zeros
zeros_array = np.zeros((3, 3))

print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
